#!/usr/bin/env osascript -l JavaScript

function run(args) {
    var languages = {
        "items":
            { "title": "Automatic detection", "subtitle": "auto" },
            { "title": "(Afan)/Oromo", "subtitle": "om" },
            { "title": "Abkhazian", "subtitle": "ab" },
            { "title": "Afar", "subtitle": "aa" },
            { "title": "Afrikaans", "subtitle": "af" },
            { "title": "Akan", "subtitle": "ak" },
            { "title": "Albanian", "subtitle": "sq" },
            { "title": "Amharic", "subtitle": "am" },
            { "title": "Arabic", "subtitle": "ar" },
            { "title": "Aragonese", "subtitle": "an" },
            { "title": "Armenian", "subtitle": "hy" },
            { "title": "Assamese", "subtitle": "as" },
            { "title": "Avaric", "subtitle": "av" },
            { "title": "Avestan", "subtitle": "ae" },
            { "title": "Aymara", "subtitle": "ay" },
            { "title": "Azeri", "subtitle": "az" },
            { "title": "Bambara", "subtitle": "bm" },
            { "title": "Bashkir", "subtitle": "ba" },
            { "title": "Basque", "subtitle": "eu" },
            { "title": "Belarusian", "subtitle": "be" },
            { "title": "Bengali", "subtitle": "bn" },
            { "title": "Bhutani", "subtitle": "dz" },
            { "title": "Bihari", "subtitle": "bh" },
            { "title": "Bislama", "subtitle": "bi" },
            { "title": "Bosnian", "subtitle": "bs" },
            { "title": "Breton", "subtitle": "br" },
            { "title": "Bulgarian", "subtitle": "bg" },
            { "title": "Burmese", "subtitle": "my" },
            { "title": "Cambodian", "subtitle": "km" },
            { "title": "Cantonese", "subtitle": "yue" },
            { "title": "Catalan", "subtitle": "ca" },
            { "title": "Chamorro", "subtitle": "ch" },
            { "title": "Chechen", "subtitle": "ce" },
            { "title": "Chichewa", "subtitle": "ny" },
            { "title": "Chinese", "subtitle": "zh" },
            { "title": "Chinese (Simplified)", "subtitle": "zh-CN" },
            { "title": "Chinese (Traditional)", "subtitle": "zh-TW" },
            { "title": "Church Slavonic", "subtitle": "cu" },
            { "title": "Chuvash", "subtitle": "cv" },
            { "title": "Cornish", "subtitle": "kw" },
            { "title": "Corsican", "subtitle": "co" },
            { "title": "Cree", "subtitle": "cr" },
            { "title": "Croatian", "subtitle": "hr" },
            { "title": "Czech", "subtitle": "cs" },
            { "title": "Danish", "subtitle": "da" },
            { "title": "Divehi", "subtitle": "dv" },
            { "title": "Dutch", "subtitle": "nl" },
            { "title": "Dutch (Belgium)", "subtitle": "nl-BE" },
            { "title": "Dutch (Netherlands)", "subtitle": "nl-NL" },
            { "title": "Elvish (Sindarin)", "subtitle": "sjn" },
            { "title": "Emoji Speak", "subtitle": "emoji" },
            { "title": "English", "subtitle": "en" },
            { "title": "Esperanto", "subtitle": "eo" },
            { "title": "Estonian", "subtitle": "et" },
            { "title": "Ewe", "subtitle": "ee" },
            { "title": "Faroese", "subtitle": "fo" },
            { "title": "Farsi", "subtitle": "fa" },
            { "title": "Fiji", "subtitle": "fj" },
            { "title": "Finnish", "subtitle": "fi" },
            { "title": "French", "subtitle": "fr" },
            { "title": "Frisian", "subtitle": "fy" },
            { "title": "Fulah", "subtitle": "ff" },
            { "title": "FYRO Macedonian", "subtitle": "mk" },
            { "title": "Gaelic", "subtitle": "gd" },
            { "title": "Galician", "subtitle": "gl" },
            { "title": "Ganda", "subtitle": "lg" },
            { "title": "Georgian", "subtitle": "ka" },
            { "title": "German", "subtitle": "de" },
            { "title": "Greek", "subtitle": "el" },
            { "title": "Greenlandic", "subtitle": "kl" },
            { "title": "Guarani", "subtitle": "gn" },
            { "title": "Gujarati", "subtitle": "gu" },
            { "title": "Haitian", "subtitle": "ht" },
            { "title": "Hausa", "subtitle": "ha" },
            { "title": "Hebrew", "subtitle": "he" },
            { "title": "Hindi", "subtitle": "hi" },
            { "title": "Hungarian", "subtitle": "hu" },
            { "title": "Icelandic", "subtitle": "is" },
            { "title": "Igbo", "subtitle": "ig" },
            { "title": "Indonesian", "subtitle": "id" },
            { "title": "Irish", "subtitle": "ga" },
            { "title": "Italian", "subtitle": "it" },
            { "title": "Japanese", "subtitle": "ja" },
            { "title": "Javanese", "subtitle": "jv" },
            { "title": "Kannada", "subtitle": "kn" },
            { "title": "Kazakh", "subtitle": "kk" },
            { "title": "Korean", "subtitle": "ko" },
            { "title": "Kurdish", "subtitle": "ku" },
            { "title": "Latin", "subtitle": "la" },
            { "title": "Latvian", "subtitle": "lv" },
            { "title": "Lithuanian", "subtitle": "lt" },
            { "title": "Malay", "subtitle": "ms" },
            { "title": "Malayalam", "subtitle": "ml" },
            { "title": "Maltese", "subtitle": "mt" },
            { "title": "Maori", "subtitle": "mi" },
            { "title": "Marathi", "subtitle": "mr" },
            { "title": "Mongolian", "subtitle": "mn" },
            { "title": "Nepali", "subtitle": "ne" },
            { "title": "Norwegian", "subtitle": "no" },
            { "title": "Pashto", "subtitle": "ps" },
            { "title": "Polish", "subtitle": "pl" },
            { "title": "Portuguese", "subtitle": "pt" },
            { "title": "Punjabi", "subtitle": "pa" },
            { "title": "Quechua", "subtitle": "qu" },
            { "title": "Romanian", "subtitle": "ro" },
            { "title": "Russian", "subtitle": "ru" },
            { "title": "Sanskrit", "subtitle": "sa" },
            { "title": "Serbian", "subtitle": "sr" },
            { "title": "Slovak", "subtitle": "sk" },
            { "title": "Slovenian", "subtitle": "sl" },
            { "title": "Spanish", "subtitle": "es" },
            { "title": "Swahili", "subtitle": "sw" },
            { "title": "Swedish", "subtitle": "sv" },
            { "title": "Tamil", "subtitle": "ta" },
            { "title": "Telugu", "subtitle": "te" },
            { "title": "Thai", "subtitle": "th" },
            { "title": "Turkish", "subtitle": "tr" },
            { "title": "Ukrainian", "subtitle": "uk" },
            { "title": "Urdu", "subtitle": "ur" },
            { "title": "Uzbek", "subtitle": "uz" },
            { "title": "Vietnamese", "subtitle": "vi" },
            { "title": "Welsh", "subtitle": "cy" },
            { "title": "Xhosa", "subtitle": "xh" },
            { "title": "Yiddish", "subtitle": "yi" },
            { "title": "Yoruba", "subtitle": "yo" },
            { "title": "Zulu", "subtitle": "zu" }
        }

    return JSON.stringify(languages);
}